[package]
name = "adulting"
version = "0.1.1"
edition = "2021"
license = "Unlicense"
repository = "https://github.com/ismail/adulting"
description = "A program to print one rule at a time from The 25 Principles for Adult Behavior: John Perry Barlow."

[dependencies]
rand = ">=0.8.5"

